// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    raise_pool
    (
        init => init
        upgrade => upgrade
        getSoftCap => soft_cap
        getHardCap => hard_cap
        getMinDeposit => min_deposit
        getMaxDeposit => max_deposit
        getDepositIncrements => deposit_increments
        getStartDate => start_date
        getEndDate => end_date
        getRefundEnabled => refund_enabled
        getPlatfromFeeWallet => platform_fee_wallet
        getGroupFeeWallet => group_fee_wallet
        getSignerAddress => signer_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
