// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    factory
    (
        init => init
        upgrade => upgrade
        setSourceContract => set_source_contract
        deployRaisePool => deploy_raise_pool
        setContractCreationEnabled => set_raise_pool_enabled
        getSourceContract => source_contract
        getContractCreationEnabled => raise_pool_enabled
        getAddressToDeployer => address_to_deployer
        getPoolIdToAddress => pool_id_to_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
