[package]
name = "stake-pool-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.stake-pool]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.4"
default-features = false
